import { createFileRoute, Link } from "@tanstack/react-router";
import { RefreshCw, ShieldAlert, Users, Ticket, Activity } from "lucide-react";
import { collection, getDocs, limit, orderBy, query } from "firebase/firestore";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { AppShell } from "../components/app-shell";
import { firestore, runAdminSync, subscribeToAuth } from "../lib/firebase";
import { getUserProfile } from "../lib/firestore";
export const Route=createFileRoute("/admin")({component:Admin});
function Admin(){const[user,setUser]=useState<any>(null);const[profile,setProfile]=useState<any>(null);const[logs,setLogs]=useState<any[]>([]);const[busy,setBusy]=useState(false);useEffect(()=>subscribeToAuth(setUser),[]);useEffect(()=>{if(user)getUserProfile(user.uid).then(setProfile)},[user]);const loadLogs=()=>getDocs(query(collection(firestore,"api_logs"),orderBy("createdAt","desc"),limit(20))).then(s=>setLogs(s.docs.map(d=>({id:d.id,...d.data()})))).catch(()=>{});useEffect(()=>{if(profile?.role==="ADMIN"||profile?.role==="SUPER_ADMIN")loadLogs()},[profile]);if(!user||!profile)return <AppShell user={user}><div className="page narrow"><div className="empty"><ShieldAlert size={28}/><b>Admin access only.</b><Link to="/login">Ingia</Link></div></div></AppShell>;if(!["ADMIN","SUPER_ADMIN"].includes(profile.role))return <AppShell user={user}><div className="page narrow"><div className="empty"><ShieldAlert size={28}/><b>Huna ruhusa ya admin.</b></div></div></AppShell>;return <AppShell user={user}><div className="page"><div className="page-title"><div><span className="eyebrow">CONTROL CENTER</span><h1>Admin dashboard</h1><p>Trusted operations pekee: sync, moderation na system health.</p></div><button className="btn btn-primary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await runAdminSync();toast.success("Sync: "+r.count+" matches, "+r.settled+" tickets settled.");await loadLogs()}catch(e){toast.error(e instanceof Error?e.message:"Sync imeshindikana.")}finally{setBusy(false)}}}><RefreshCw size={17}/> {busy?"Syncing...":"Sync sports now"}</button></div><div className="stat-grid admin-stats"><div className="stat-box"><Activity/><small>API</small><b>Server-side</b></div><div className="stat-box"><Users/><small>Role</small><b>{profile.role}</b></div><div className="stat-box"><Ticket/><small>Results</small><b>Automated</b></div></div><div className="admin-grid"><div className="panel"><div className="panel-head"><h3>Modules</h3></div><div className="admin-links"><span>Users • moderation</span><span>Tickets • feature / hide</span><span>Matches • sync status</span><span>Results • settlement</span><span>Reports • abuse controls</span><span>VIP • payments architecture</span></div></div><div className="panel"><div className="panel-head"><h3>Recent API logs</h3></div>{logs.length?<div className="log-list">{logs.map(l=><div key={l.id}><b>{l.type}</b><span>{l.ok===false?"FAILED":"OK"}</span><small>{l.error??"Completed"}</small></div>)}</div>:<div className="empty compact">Hakuna logs bado.</div>}</div></div></div></AppShell>}
