import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Plus, Trash2, ShieldCheck, ChevronLeft } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import type { User } from "firebase/auth";
import { AppShell } from "../components/app-shell";
import { subscribeToAuth } from "../lib/firebase";
import { createTicket, getUserProfile, listMatches } from "../lib/firestore";
import { calculateTotalOdds, type MarketKey, type Selection } from "../lib/betting";

export const Route=createFileRoute("/create-ticket")({component:CreateTicket});
const marketLabels: Record<MarketKey,string>={"1X2":"1X2","DOUBLE_CHANCE":"Double Chance","OVER_UNDER":"Over/Under","BTTS":"Both Teams To Score","DRAW_NO_BET":"Draw No Bet","HANDICAP":"Handicap","HALF_TIME":"Half Time","FULL_TIME":"Full Time"};

function CreateTicket(){
 const nav=useNavigate(); const[user,setUser]=useState<User|null>(null); const[matches,setMatches]=useState<any[]>([]); const[title,setTitle]=useState(""); const[description,setDescription]=useState(""); const[sport,setSport]=useState("Football"); const[risk,setRisk]=useState<"LOW"|"MEDIUM"|"HIGH">("MEDIUM"); const[access,setAccess]=useState<"FREE"|"VIP">("FREE"); const[visibility,setVisibility]=useState<"PUBLIC"|"PRIVATE">("PUBLIC"); const[chosen,setChosen]=useState<Selection[]>([]); const[busy,setBusy]=useState(false);
 useEffect(()=>subscribeToAuth(setUser),[]); useEffect(()=>{listMatches().then(setMatches).catch(e=>toast.error(e instanceof Error?e.message:"Mechi hazijapatikana."))},[]);
 const totalOdds=useMemo(()=>calculateTotalOdds(chosen),[chosen]);
 const add=(match:any, market:MarketKey, option:any)=>{const item:Selection={matchId:match.id,market,line:option.line??null,prediction:option.prediction,odds:Number(option.odds),homeTeam:match.homeTeamName,awayTeam:match.awayTeamName,kickoffAt:match.kickoffAt,leagueName:match.leagueName};if(!item.odds||item.odds<=1){toast.error("Odds ya selection hii haipo kwenye Sports API.");return}setChosen(current=>current.some(x=>x.matchId===item.matchId&&x.market===item.market&&x.prediction===item.prediction)?current:[...current,item]);};
 return <AppShell user={user}><div className="page narrow"><Link className="back-link" to="/"><ChevronLeft size={17}/> Nyumbani</Link><div className="page-title"><div><span className="eyebrow">TICKET BUILDER</span><h1>Tengeneza mkeka</h1><p>Selections hutoka kwenye matches na odds zilizoingizwa na Sports API.</p></div><div className="odds-box"><small>Total odds</small><b>{totalOdds.toFixed(2)}</b><span>{chosen.length} selections</span></div></div>{!user&&<div className="alert"><ShieldCheck size={18}/> Ingia kwanza ili uweze kuhifadhi na kuchapisha mkeka. <Link to="/login">Ingia</Link></div>}
 <div className="builder-grid"><section className="panel"><div className="panel-head"><h3>1. Chagua mechi</h3><span>{matches.length} loaded</span></div>{matches.length===0?<div className="empty"><ShieldCheck size={25}/><b>Hakuna mechi za kuchagua.</b><span>Hii si demo data. Admin lazima aweke SPORTS_API_KEY na ku-run synchronization.</span></div>:<div className="match-builder">{matches.map(match=><div className="match-builder-card" key={match.id}><div className="match-head"><div><small>{match.leagueName??"League"} • {match.status??"SCHEDULED"}</small><b>{match.homeTeamName} <span>vs</span> {match.awayTeamName}</b></div><time>{new Date(match.kickoffAt).toLocaleString("sw-TZ",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"short"})}</time></div><div className="market-grid">{(match.markets??[]).map((market:any)=><div className="market" key={market.market}><small>{marketLabels[market.market as MarketKey]??market.market}</small><div>{(market.options??[]).map((option:any)=><button key={option.prediction} onClick={()=>add(match,market.market,option)}><span>{option.prediction}</span><b>{Number(option.odds).toFixed(2)}</b><Plus size={14}/></button>)}</div></div>)}</div></div>)}</div>}</section>
 <aside className="panel ticket-side"><div className="panel-head"><h3>2. Publish</h3></div><label>Kichwa<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Mfano: Weekend accumulator"/></label><label>Maelezo<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></label><div className="form-grid"><label>Risk<select value={risk} onChange={e=>setRisk(e.target.value as any)}><option value="LOW">Ndogo</option><option value="MEDIUM">Kati</option><option value="HIGH">Juu</option></select></label><label>Access<select value={access} onChange={e=>setAccess(e.target.value as any)}><option value="FREE">FREE</option><option value="VIP">VIP</option></select></label></div><label>Visibility<select value={visibility} onChange={e=>setVisibility(e.target.value as any)}><option value="PUBLIC">Public</option><option value="PRIVATE">Private</option></select></label><div className="selected-list">{chosen.length?chosen.map((item,i)=><div key={i}><div><b>{item.homeTeam} vs {item.awayTeam}</b><small>{marketLabels[item.market]} • {item.prediction}</small></div><strong>{item.odds.toFixed(2)}</strong><button onClick={()=>setChosen(c=>c.filter((_,idx)=>idx!==i))}><Trash2 size={15}/></button></div>):<div className="empty compact">Chagua selections upande wa kushoto.</div>}</div><button className="btn btn-primary full" disabled={!user||!title.trim()||chosen.length===0||busy} onClick={async()=>{if(!user)return;setBusy(true);try{const profile=await getUserProfile(user.uid);if(!profile)throw new Error("Profile haijapatikana.");const id=await createTicket({uid:user.uid,username:String(profile.username??user.email?.split("@")[0]??"user"),displayName:String(profile.displayName??user.displayName??"User"),photoURL:profile.photoURL,title,description,sport,risk,visibility,access,selections:chosen});toast.success("Mkeka umechapishwa.");nav({to:"/tickets/$ticketId",params:{ticketId:id}})}catch(e){toast.error(e instanceof Error?e.message:"Imeshindikana kuchapisha.")}finally{setBusy(false)}}}>{busy?"Inachapisha...":"Publish ticket"}</button><small className="fine-print">Baada ya kickoff ya selection, selection hiyo inakuwa locked na settlement engine pekee ndiyo inaweza kubadilisha status.</small></aside></div></div></AppShell>;
}