import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { LogOut, Plus, ShieldCheck, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import type { User } from "firebase/auth";
import { toast } from "sonner";
import { AppShell } from "../components/app-shell";
import { firestore, logout, subscribeToAuth } from "../lib/firebase";
import { getUserProfile } from "../lib/firestore";
import { collection, getDocs, query, where } from "firebase/firestore";
export const Route=createFileRoute("/dashboard")({component:Dashboard});
function Dashboard(){const nav=useNavigate();const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<any>(null);const[tickets,setTickets]=useState<any[]>([]);useEffect(()=>subscribeToAuth(setUser),[]);useEffect(()=>{if(!user){setProfile(null);return}getUserProfile(user.uid).then(setProfile);getDocs(query(collection(firestore,"tickets"),where("creatorId","==",user.uid))).then(s=>setTickets(s.docs.map(d=>({id:d.id,...d.data()})))).catch(e=>toast.error(e instanceof Error?e.message:"Tickets hazijasomeka."))},[user]);if(!user)return <AppShell><div className="page narrow"><div className="empty"><ShieldCheck size={26}/><b>Ingia ili kufungua dashboard.</b><Link className="btn btn-primary" to="/login">Ingia</Link></div></div></AppShell>;const stats=[["Tickets",profile?.ticketCount??tickets.length],["Won",profile?.wonCount??0],["Lost",profile?.lostCount??0],["Win rate",(profile?.winRate??0)+"%"]];return <AppShell user={user}><div className="page narrow"><section className="profile-hero"><div className="ticket-avatar large">{profile?.displayName?.[0]??"U"}</div><div><span className="eyebrow">MY PROFILE</span><h1>{profile?.displayName??user.displayName??"User"}</h1><p>@{profile?.username??"user"} • {profile?.bio??"Betting community member"}</p></div><button className="btn btn-secondary" onClick={async()=>{await logout();nav({to:"/"})}}><LogOut size={16}/> Toka</button></section><div className="stat-grid">{stats.map(([label,value])=><div className="stat-box" key={String(label)}><small>{label}</small><b>{String(value)}</b></div>)}</div><div className="section-toolbar"><div><span className="eyebrow">YOUR TICKETS</span><h2>Mikeka yako</h2></div><Link className="btn btn-primary" to="/create-ticket"><Plus size={17}/> Tengeneza</Link></div><div className="panel">{tickets.length?<div className="ticket-list">{tickets.map(t=><Link className="ticket" to="/tickets/$ticketId" params={{ticketId:t.id}} key={t.id}><div className="ticket-avatar">{t.title?.[0]??"T"}</div><div className="ticket-main"><div className="ticket-line"><b>{t.title}</b><span className={`status status-${String(t.status).toLowerCase()}`}>{t.status}</span></div><small>{t.selectionCount} selections • {t.sport}</small><div className="ticket-meta"><strong>{Number(t.totalOdds).toFixed(2)} odds</strong><span>{t.visibility}</span></div></div></Link>)}</div>:<div className="empty"><Trophy size={25}/><b>Bado hujachapisha mkeka.</b><Link className="btn btn-primary" to="/create-ticket">Jenga wa kwanza</Link></div>}</div></div></AppShell>}
