import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Bookmark, Heart, Send, ShieldCheck, UserPlus } from "lucide-react";
import { collection, getDocs, query, where } from "firebase/firestore";
import { useEffect, useState } from "react";
import type { User } from "firebase/auth";
import { toast } from "sonner";
import { AppShell } from "../../components/app-shell";
import { firestore, subscribeToAuth } from "../../lib/firebase";
import { addComment, followUser, getTicket, toggleLike, toggleSave } from "../../lib/firestore";

export const Route=createFileRoute("/tickets/$ticketId")({component:TicketDetails});
function TicketDetails(){const{ticketId}=Route.useParams();const[user,setUser]=useState<User|null>(null);const[ticket,setTicket]=useState<any>(null);const[comments,setComments]=useState<any[]>([]);const[liked,setLiked]=useState(false);const[saved,setSaved]=useState(false);const[comment,setComment]=useState("");const[busy,setBusy]=useState(false);
const load=async()=>{const t=await getTicket(ticketId);setTicket(t);const cs=await getDocs(query(collection(firestore,"comments"),where("ticketId","==",ticketId)));setComments(cs.docs.map(d=>({id:d.id,...d.data()})));if(user){const[l,s]=await Promise.all([getDocs(query(collection(firestore,"likes"),where("ticketId","==",ticketId),where("userId","==",user.uid))),getDocs(query(collection(firestore,"savedTickets"),where("ticketId","==",ticketId),where("userId","==",user.uid)))]);setLiked(!l.empty);setSaved(!s.empty);}};useEffect(()=>subscribeToAuth(setUser),[]);useEffect(()=>{load().catch(e=>toast.error(e instanceof Error?e.message:"Ticket haijapatikana."))},[ticketId,user]);
if(!ticket)return <AppShell user={user}><div className="page"><div className="empty">Inapakia ticket...</div></div></AppShell>;
return <AppShell user={user}><div className="page narrow"><Link className="back-link" to="/"><ArrowLeft size={16}/> Rudi</Link><section className="panel ticket-detail"><div className="detail-head"><div className="ticket-avatar">{ticket.creatorName?.[0]??"W"}</div><div><span className="eyebrow">@{ticket.creatorUsername}</span><h1>{ticket.title}</h1><p>{ticket.description||"Hakuna maelezo."}</p></div><span className={`status status-${String(ticket.status).toLowerCase()}`}>{ticket.status}</span></div><div className="detail-summary"><div><small>SPORT</small><b>{ticket.sport}</b></div><div><small>ODDS</small><b>{Number(ticket.totalOdds).toFixed(2)}</b></div><div><small>RISK</small><b>{ticket.risk}</b></div><div><small>ACCESS</small><b>{ticket.access}</b></div></div><div className="selection-detail">{(ticket.selections??[]).map((s:any)=><div className="selection-row" key={s.id}><div><b>{s.homeTeam} <span>vs</span> {s.awayTeam}</b><small>{s.market} • {s.prediction}</small></div><strong>{Number(s.odds).toFixed(2)}</strong><span className={`status status-${String(s.status).toLowerCase()}`}>{s.status}</span></div>)}</div><div className="detail-actions"><button className={liked?"engaged":""} disabled={!user} onClick={async()=>{if(!user)return;setLiked(await toggleLike(ticketId,user.uid))}}><Heart size={18} fill={liked?"currentColor":"none"}/> Like</button><button className={saved?"engaged":""} disabled={!user} onClick={async()=>{if(!user)return;setSaved(await toggleSave(ticketId,user.uid))}}><Bookmark size={18} fill={saved?"currentColor":"none"}/> Save</button><button disabled={!user} onClick={async()=>{if(!user)return;try{await followUser(ticket.creatorId,user.uid);toast.success("Follow imebadilishwa.")}catch(e){toast.error(e instanceof Error?e.message:"Imeshindikana.")}}}><UserPlus size={18}/> Follow</button></div></section><section className="panel comments"><div className="panel-head"><div><span className="eyebrow">COMMUNITY</span><h3>Comments</h3></div></div>{user?<div className="comment-box"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Andika comment..." /><button disabled={busy} onClick={async()=>{if(!user)return;setBusy(true);try{await addComment(ticketId,user.uid,user.displayName??"User",comment);setComment("");await load();}catch(e){toast.error(e instanceof Error?e.message:"Comment imeshindikana.")}finally{setBusy(false)}}}><Send size={17}/></button></div>:<div className="alert"><ShieldCheck size={17}/> Ingia ili ku-like, ku-save au ku-comment. <Link to="/login">Ingia</Link></div>}{comments.length?<div className="comment-list">{comments.map(c=><div key={c.id}><div className="comment-avatar">{c.authorName?.[0]??"U"}</div><div><b>{c.authorName}</b><p>{c.text}</p></div></div>)}</div>:<div className="empty compact">Hakuna comments bado.</div>}</section></div></AppShell>;
}