import {
  BadgeCheck,
  Baby,
  CarFront,
  Contact,
  Copy,
  FileBadge,
  FileWarning,
  HeartHandshake,
  Image,
  Landmark,
  Music2,
  Palette,
  Plane,
  QrCode,
  Radio,
  ScanFace,
  Search,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Ticket,
  Trophy,
  Tv,
  UserRoundPen,
  Vote,
} from "lucide-react";

const icons: Record<string, React.ElementType> = {
  "file-badge": FileBadge,
  "badge-check": BadgeCheck,
  contact: Contact,
  "qr-code": QrCode,
  vote: Vote,
  store: Store,
  ticket: Ticket,
  copy: Copy,
  "car-front": CarFront,
  search: Search,
  landmark: Landmark,
  baby: Baby,
  plane: Plane,
  "heart-handshake": HeartHandshake,
  "file-warning": FileWarning,
  "music-2": Music2,
  image: Image,
  smartphone: Smartphone,
  "scan-face": ScanFace,
  "user-round-pen": UserRoundPen,
  palette: Palette,
  radio: Radio,
  trophy: Trophy,
  star: Star,
  tv: Tv,
};

export function ServiceIcon({ name, size = 20 }: { name: string; size?: number }) {
  const Component = icons[name] ?? Sparkles;
  return <Component size={size} strokeWidth={1.9} />;
}
